// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orhiqemqxpqlkadywuvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yaGlxZW1xeHBxbGthZHl3dXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDMzNTAsImV4cCI6MjA1NTIxOTM1MH0.2QTx2t7ut5uiv7iNNWg4eT6j4qIsMU6zcdzN8PqmNhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);